"""Adding initial tables

Revision ID: 4f310004f218
Revises: 
Create Date: 2015-10-23 16:08:21.396455

"""

# revision identifiers, used by Alembic.
revision = '4f310004f218'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('local_drive_capacity', sa.Integer(), nullable=True),
    sa.Column('psu_capacity', sa.Integer(), nullable=True),
    sa.Column('psu_size', sa.String(length=36), nullable=True),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.Column('cpu_architecture', sa.String(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('deploy_kernel', sa.String(), nullable=True),
    sa.Column('deploy_ramdisk', sa.String(), nullable=True),
    sa.Column('ipmi_address', sa.String(), nullable=True),
    sa.Column('ipmi_password', sa.String(), nullable=True),
    sa.Column('impi_username', sa.String(), nullable=True),
    sa.Column('impi_priv_level', sa.String(), nullable=True),
    sa.Column('ipmi_mac_address', sa.String(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('deployed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ipmi_mac_address', name='uniq_servers0impmimacaddress'),
    sa.UniqueConstraint('name', name='uniq_servers0name'),
    sa.UniqueConstraint('uuid', name='uniq_servers0uuid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    op.drop_table('reservations')
    ### end Alembic commands ###
